import { SupabaseClient } from "@supabase/supabase-js";
import storeFile from "./store-file";

/**
 * Creates a new file entry in the database and stores the file in storage.
 * @param file - The file to be stored
 * @param isAIgenerated - Boolean indicating whether the file was generated by AI
 * @param bucketName - The name of the storage bucket where the file will be stored
 * @param userId - The ID of the user who owns the file
 * @param supabase - The Supabase client instance
 * @returns Promise<string> - Returns the file ID of the created file
 * @throws Error if file creation or storage fails
 */
export default async function createFile(
  file: File,
  isAIgenerated: boolean,
  bucketName: string,
  userId: string,
  supabase: SupabaseClient<any, any, any>
) {
  try {
    /* Save file in storage */
    const objectId = await storeFile(file, bucketName, userId, supabase);

    /* Create file */
    const { data, error } = await supabase
      .from("file")
      .insert({
        file_id: objectId,
        isAIgenerated,
      })
      .select();

    if (error) {
      throw new Error(error.message);
    }
    return data[0].file_id;
  } catch (error) {
    throw new Error(
      error instanceof Error ? error.message : "Failed to create file"
    );
  }
}
